version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        container_name: mvc
        working_dir: /app
        volumes:
            - '.:/app'
            - '${PATH_PHP:-/home/usuario01/r2-projetos}/php/8.1/phpdocker/nginx/nginx_php.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - app-networks-r2
    php-fpm:
        build:  '${PATH_PHP:-/home/usuario01/r2-projetos}/php/8.1/phpdocker/php-fpm'
        working_dir: /app
        container_name: php8.1-mvc
        volumes:
            - '.:/app'
            - '${PATH_PHP:-/home/usuario01/r2-projetos}/php/8.1/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - app-networks-r2
networks:
    app-networks-r2:
        driver: bridge
